# Site owner settings
title: Justin Hill
email: justinmhill@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog and portfolio site focusing on
  technology, web development, and education.
twitter_username: justinmhill
github_username:  jmhill

# Site structure
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justinmhill.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title.html # the url structure for posts

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page

# Build settings
markdown: kramdown
